security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9091/oauth/check_token
    client:
      client-id: client
      client-secret: client
      access-token-uri: http://localhost:9091/oauth/token
      scope: password